# ---------------------------------------------------------------------------
#  Risk Platform: Amazon DynamoDB (Local)
# ---------------------------------------------------------------------------
multiclouddb.provider=dynamo
multiclouddb.connection.endpoint=http://localhost:8000
multiclouddb.connection.region=us-east-1
multiclouddb.auth.accessKeyId=fakeMyKeyId
multiclouddb.auth.secretAccessKey=fakeSecretAccessKey
