# ---------------------------------------------------------------------------
#  Multicloud DB TODO App - DynamoDB Local Configuration
# ---------------------------------------------------------------------------
# Usage:  -Dtodo.config=todo-app-dynamo.properties
#
multiclouddb.provider=dynamo

# --- Application Settings ---------------------------------------------------
multiclouddb.database=local
multiclouddb.collection=todos

# --- Amazon DynamoDB (Local) ------------------------------------------------
multiclouddb.connection.endpoint=http://localhost:8000
multiclouddb.connection.region=us-east-1

# DynamoDB Local accepts any credentials
multiclouddb.auth.accessKeyId=fakeMyKeyId
multiclouddb.auth.secretAccessKey=fakeSecretAccessKey
